import "./globals.css";
import Providers from "@/lib/Providers/Providers";
import { Toaster } from "sonner";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "GYM Class",
  description: "Generated by Gym Class Scheduling",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <div>
            <Toaster position="top-center" />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
